// build-index.mjs
// Regenerates INDEX.md catalogs from component header blocks, so AI assistants
// can pick components by USE WHEN without reading whole folders.
// Usage: npm run index
// Fails (exit 1) if any component .tsx lacks the header convention — this is
// the lint gate that keeps the catalogs trustworthy.

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const GENERATED_NOTE =
  "<!-- Generated by `npm run index` from component headers. Do not edit by hand. -->";

// Directory groups that each get an INDEX.md. Patterns/components group by subfolder.
const GROUPS = [
  { dir: "primitives", title: "Primitives" },
  { dir: "components", title: "Shared components", bySubdir: true },
  { dir: "effects", title: "Effects" },
  { dir: "patterns", title: "Patterns (à la carte)", bySubdir: true, emptyNote: "_(empty — see [CONTRIBUTING.md](../CONTRIBUTING.md) to add patterns)_" },
];

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith(".tsx")) out.push(full);
  }
  return out;
}

function parseHeader(file) {
  const src = readFileSync(file, "utf8");
  const m = src.match(/\/\*\*([\s\S]*?)\*\//);
  if (!m) return null;
  const lines = m[1].split("\n").map((l) => l.replace(/^\s*\*\s?/, "").trim());
  const fields = {};
  let current = null;
  for (const line of lines) {
    const fm = line.match(/^(USE WHEN|INDUSTRY FIT|PAIRS WITH|DEPS|NOTE)\s*:\s*(.*)$/i);
    if (fm) {
      current = fm[1].toUpperCase();
      fields[current] = fm[2];
    } else if (current && line && !line.endsWith(".tsx")) {
      fields[current] += " " + line;
    }
  }
  if (!fields["USE WHEN"]) return null;
  return fields;
}

function indexLines(files, base) {
  return files
    .sort()
    .map((f) => {
      const h = headers.get(f);
      const name = relative(base, f).split(sep).join("/");
      return `- **${name}** — ${h["USE WHEN"]}`;
    });
}

// --- Scan everything and lint ---
const allDirs = ["primitives", "components", "effects", "patterns", "industries"]
  .map((d) => join(ROOT, d))
  .filter(existsSync);
const allFiles = allDirs.flatMap(walk);
const headers = new Map();
const missing = [];
for (const f of allFiles) {
  const h = parseHeader(f);
  if (h) headers.set(f, h);
  else missing.push(relative(ROOT, f));
}
if (missing.length) {
  console.error("MISSING USE WHEN header (add the header block, then re-run):");
  for (const f of missing) console.error("  " + f);
  process.exit(1);
}

// --- Write group indexes ---
let written = 0;
for (const g of GROUPS) {
  const dir = join(ROOT, g.dir);
  if (!existsSync(dir)) continue;
  const files = allFiles.filter((f) => f.startsWith(dir + sep));
  let body;
  if (!files.length) {
    body = g.emptyNote ?? "_(empty)_";
  } else if (g.bySubdir) {
    const bySub = {};
    for (const f of files) {
      const sub = relative(dir, f).split(sep)[0];
      const key = sub.endsWith(".tsx") ? "." : sub;
      (bySub[key] ??= []).push(f);
    }
    body = Object.keys(bySub)
      .sort()
      .map((sub) => `### ${sub === "." ? g.dir : sub}\n\n${indexLines(bySub[sub], dir).join("\n")}`)
      .join("\n\n");
  } else {
    body = indexLines(files, dir).join("\n");
  }
  writeFileSync(
    join(dir, "INDEX.md"),
    `# ${g.title} — catalog\n\n${GENERATED_NOTE}\n\nPick by USE WHEN, then read only the chosen file.\n\n${body}\n`
  );
  written++;
}

// --- Per-industry section indexes ---
const industriesDir = join(ROOT, "industries");
if (existsSync(industriesDir)) {
  for (const entry of readdirSync(industriesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const secDir = join(industriesDir, entry.name, "sections");
    if (!existsSync(secDir)) continue;
    const files = allFiles.filter((f) => f.startsWith(secDir + sep));
    writeFileSync(
      join(secDir, "INDEX.md"),
      `# ${entry.name} sections — catalog\n\n${GENERATED_NOTE}\n\nPick by USE WHEN, then read only the chosen file. Follow ../DIRECTION.md exactly.\n\n${indexLines(files, secDir).join("\n")}\n`
    );
    written++;
  }
}

console.log(`Indexed ${allFiles.length} components into ${written} INDEX.md catalogs.`);
